[package]
name = "resolver"
version = "0.1.0"

[dependencies]
starknet = "2.3.1"
naming = { git = "https://github.com/starknet-id/naming.git", branch = "feat/add_ccip" }
openzeppelin = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v0.8.0-beta.0" }
identity = { git = "https://github.com/starknet-id/identity.git", rev = "2e8fecab0d9a971710e8efb21abc25fb7825ee09" }

[[target.starknet-contract]]
# Enable Sierra codegen.
sierra = true

# Enable CASM codegen.
casm = true

# Emit Python-powered hints in order to run compiled CASM class with legacy Cairo VM.
casm-add-pythonic-hints = true

# build-external-contracts = ["identity::identity::main::Identity"]
